In [4]:
from bs4 import BeautifulSoup
import lxml
import requests
# 1달러는 지금 몇원일지...?!
def korean_won():
    r = requests.get('https://finance.naver.com/marketindex/?tabSel=exchange#tab_section')
    soup = BeautifulSoup(r.content, 'lxml')

    get_current = soup.find("span", class_="value").get_text()
    get_current = get_current.replace(',', '')
    get_current = float(get_current)

    return get_current

In [7]:
print(int(korean_won() * 100))

130800

In [9]:
import pandas as pd
data = pd.read_csv('fill_season_catagory.csv')
data

,pk,model,name,thumbnail,gender,top_notes,heart_notes,base_notes,seasons,availability,brand,categories,price
0,26120003,perfumes.perfume,X-Centric,26120003.jpg,1,"[178, 224, 229, 292, 388, 395, 646]","[358, 545, 785]","[26, 193, 624, 692]","[1, 2, 3, 4]",True,895,[3],21.00
1,26120006,perfumes.perfume,GFT,26120006.jpg,1,"[96, 515, 562]","[292, 512, 886]","[193, 624, 649]",[3],True,1170,"[3, 5, 8]",62.00
2,26120008,perfumes.perfume,Citron Citron,26120008.jpg,0,"[515, 530, 660]","[82, 604]","[178, 193, 649]","[2, 3]",True,2054,[5],99.07
3,26120015,perfumes.perfume,30cc / 50cc / 100cc,26120015.jpg,1,"[96, 388]","[45, 473, 793, 896]","[624, 649]",[3],True,642,[5],22.67
4,26120019,perfumes.perfume,1881 pour Homme,26120019.jpg,1,"[82, 96, 237, 292, 481, 512, 515, 793, 886]","[102, 785, 966]","[26, 808]","[1, 3]",True,610,[3],15.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14230,26150917,perfumes.perfume,Love Bird,26150917.jpg,0,"[250, 376, 669, 692]",[],[],"[1, 2, 3, 4]",True,445,[11],197.53
14231,26153653,perfumes.perfume,Mango Mojito,26153653.jpg,0,[876],[],[],"[1, 2, 3, 4]",True,1155,[11],125.32
14232,26153756,perfumes.perfume,Elements of Man : Passion,26153756.jpg,1,"[26, 250, 356, 472, 796, 800]",[],[],"[1, 2, 3, 4]",True,976,[11],131.81
14233,26157654,perfumes.perfume,Come Undone,26157654.jpg,0,[903],[],[],"[1, 2, 3, 4]",True,771,[11],125.00
14234,26159041,perfumes.perfume,Tandem,26159041.jpg,0,[611],[],[],"[1, 2, 3, 4]",True,2465,[11],267.00

In [13]:
money_list = []
won = korean_won()
for price in data['price']:
    money = won * price
    money_list.append(money)
    
print(int(money_list[0]))
print(len(money_list))

27510
14235